services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - openwebui-data:/app/backend/data
    ports:
      - 8090:8080
    environment:
      - 'ENABLE_OPENAI_API=True'
      - 'OPENAI_API_BASE_URLS=http://10.0.207.111:8000/v1'
      - 'OPENAI_API_KEYS='
      - 'ENABLE_OLLAMA_API=False'
      - 'VECTOR_DB=milvus'
      - 'MILVUS_URI=http://10.0.207.111:19530'
      - 'RAG_EMBEDDING_ENGINE=nvidia'
      - 'RAG_EMBEDDING_MODEL=NV-EmbedQA-E5-v5'
      - 'RAG_OPENAI_API_BASE_URL=http://10.0.207.111:9080/v1'
      - 'RAG_OPENAI_API_KEY=a'
      - 'RAG_EMBEDDING_BATCH_SIZE=1'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  openwebui-data: {}

